In [3]:
import torch
import torch.nn as nn

norm = nn.LayerNorm(16)

x = torch.eye(16).unsqueeze(0)
print(x.mean(dim=-1, keepdim=True))
print(x.std(dim=-1, keepdim=True))
print(norm(x))

tensor([[[0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625],
         [0.0625]]])
tensor([[[0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500],
         [0.2500]]])
tensor([[[ 3.8727, -0.2582, -0.2582, -0.2582, -0.2582, -0.2582, -0.2582,
          -0.2582, -0.2582, -0.2582, -0.2582, -0.2582, -0.2582, -0.2582,
          -0.2582, -0.2582],
         [-0.2582,  3.8727, -0.2582, -0.2582, -0.2582, -0.2582, -0.2582,
          -0.2582, -0.2582, -0.2582, -0.2582, -0.2582, -0.2582, -0.2582,
          -0.2582, -0.2582],
         [-0.2582, -0.2582,  3.8727, -